In [38]:
import pandas as pd
import json
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [39]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("sid321axn/amazon-alexa-reviews")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'amazon-alexa-reviews' dataset.
Path to dataset files: /kaggle/input/amazon-alexa-reviews

In [66]:
import os

# List files in the downloaded directory to identify the correct data file
downloaded_files = os.listdir(path)
print("Files downloaded:", downloaded_files)

# Assuming the data file is named 'amazon_alexa.tsv' or similar and is tab-separated
# You might need to adjust the filename based on the output of the listdir command
file_name = 'amazon_alexa.tsv' # This is a placeholder, check the output above
file_path = os.path.join(path, file_name)


df = pd.read_csv(file_path, delimiter="\t", quoting=3)
display(df.head())

Files downloaded: ['amazon_alexa.tsv']

   rating  ... feedback
0       5  ...        1
1       5  ...        1
2       4  ...        1
3       5  ...        1
4       5  ...        1

[5 rows x 5 columns]

In [67]:
df.shape

(3150, 5)

In [68]:
import re
import nltk
nltk.download("stopwords")
nltk.download('wordnet') # Download WordNet
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer # Use WordNetLemmatizer
# from nltk.tokenize import word_tokenize # No longer using nltk word_tokenize

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer() # Initialize Lemmatizer

def clean_text(text):
  if not isinstance(text, str): # Check if the input is a string
    return "" # Return an empty string for non-string inputs
  text = text.lower()
  text = re.sub(r'[^a-zA-z\s]','', text)
  words = text.split() # Use split() for tokenization
  words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words] # Lemmatize words and remove stop words
  return ' '.join(words)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [69]:
# Apply the clean_text function to the 'verified_reviews' column
df['cleaned_review'] = df['verified_reviews'].apply(clean_text)

display(df.head())

   rating  ...                                     cleaned_review
0       5  ...                                          love echo
1       5  ...                                              loved
2       4  ...  sometimes playing game answer question correct...
3       5  ...  lot fun thing yr old learns dinosaur control l...
4       5  ...                                              music

[5 rows x 6 columns]

In [75]:
vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df['cleaned_review'])
y = df['rating']

In [76]:
# Train Test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [77]:
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.7333333333333333

In [78]:
# OR
y_pred = model.predict(X_test)
print(y_pred)
print(accuracy_score(y_test, y_pred))

[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 3 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 4 5 5 5 5 4 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 1 5 5 5 5 5 5 5 5 5 5 5 5 5
 4 5 5 5 5 5 5 5 5 5 5 5 5 5 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 1 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 4 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 3 5 5 5 5 5 5
 5 5 5 4 5 5 5 5 5 4 5 5 5 5 5 1 5 5 5 5 5 5 5 5 5 5 5 5 4 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 4 5 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 4 5 5
 5 5 4 5 5 5 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 3 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 4 5 5 5 5 3 5 5 5 5 5 5 5 5 5
 5]
0.7333333333333333